#!/usr/bin/env ruby

$LOAD_PATH.unshift File.dirname(__FILE__)+'/lib'

require 'gst'

require 'freerec/controller/main'

if $0 == __FILE__
  Gst.init
  FreeRec::Controller::Main.new do
    Gtk.main
  end
end

