#!/usr/bin/env ruby

# FreeRec
# Copyright © 2009 FreeRec author <freerec1@gmail.com>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

lib_dir = File.dirname(__FILE__)+'/lib'
$LOAD_PATH.unshift lib_dir

require 'etc'
require 'gst'
require 'gtk2'

require 'freerec/controller/main'
require 'freerec/l18n'
require 'freerec/model/recorder'
require 'freerec/model/song-player'

Gst.init

FreeRec::L18n.init

home = Etc.getpwuid.dir

# TODO Make this configurable.
FreeRec::Model::Recorder.output_dir = home+'/freerec/recordings'
FreeRec::Model::SongPlayer.songs_dir = home+'/freerec/songs'

FreeRec::Controller::Main.new do
  Gtk.main
end

